### ISSUE TITLE
no lime active file - error

### ISSUE THREAD

**Issue by lewislepton** [jeremyfa/atom-lime#3]
i got atom to use haxe again, done a complete clean install. but on using the lime package and trying to get it running am getting into an error that pops up.
it says 'no lime file active'. though i have right clicked to make sure things are working. plus have all the required things for the haxe package to run well.

but here is the error screenshot

<img width="597" alt="screen shot 2015-11-16 at 19 17 58" src="https://cloud.githubusercontent.com/assets/11299322/11192057/cba209e2-8c96-11e5-8e47-281e0a481936.png">

**Comment by jeremyfa** [comment]
I reproduce a similar issue, checking...

**Comment by lewislepton** [comment]
cool spot ;)

**Comment by jeremyfa** [comment]
Let me know if the just published v0.3.3 fixes the issue.

**Comment by lewislepton** [comment]
boom. that seems to have worked.

many many thanks ;)
